-- =====================================================================
-- Phase 1A / Conditional fix — approval-transition authorisation.
--
-- STATUS: PREPARED, NOT APPLIED, NOT VERIFIED. APPLY ONLY IF THE
-- CONDITION IN SECTION 2 OF VERIFY_phase_1a.sql FIRES.
--
-- WHY THIS FILE EXISTS
--   The approved business rule is: only Estimators and Admins may approve
--   a quote (Sales representatives and external users may not). The
--   repository contains no definition of public.enforce_quote_state_transition()
--   — it was applied outside the repository — so its enforcement of that
--   rule could NOT be inspected from this workspace (see the audit caveat).
--   This file therefore cannot be finalised blind. It is a TEMPLATE plus a
--   guard: run it only after section 2 of VERIFY_phase_1a.sql shows the
--   live function does NOT reject sales_rep/external callers setting
--   state = 'approved'.
--
-- IF SECTION 2 SHOWS APPROVAL IS ALREADY ENFORCED SERVER-SIDE
--   Do not run anything in this file. Delete it from the deployment.
--
-- DESTRUCTIVE OPERATIONS: none. It only ALTERs configuration and re-creates
-- the wrapper-with-guard pattern without changing any allowed transition.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Step 1 (READ-ONLY, run first): obtain the live definition.
-- Paste the output into the deployment record before going further.
-- ---------------------------------------------------------------------
-- SELECT pg_get_functiondef(p.oid)
-- FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
-- WHERE n.nspname = 'public' AND p.proname = 'enforce_quote_state_transition';

-- ---------------------------------------------------------------------
-- Step 2 (READ-ONLY, run second): does the trigger function itself check
-- the caller's role before allowing state = 'approved'?
-- Look in the definition for a role check (private.has_role / a
-- user_roles lookup) on the branch that admits 'approved'.
-- If such a check exists and denies sales_rep and external: STOP HERE.
-- ---------------------------------------------------------------------

-- ---------------------------------------------------------------------
-- Step 3 (CONDITIONAL WRITE): if approval is NOT enforced, the minimal fix
-- is a wrapper function that adds the authorisation check and re-installs
-- the trigger, leaving the original function's transition logic untouched.
--
-- TEMPLATE — the DBA must align the argument names/types with the live
-- function from Step 1 before running. This block errors out (via the
-- guard) unless the DBA confirms the live signature matches.
-- ---------------------------------------------------------------------
-- BEGIN;
--
-- CREATE OR REPLACE FUNCTION public.enforce_quote_state_transition_checked()
-- RETURNS trigger
-- LANGUAGE plpgsql
-- SECURITY DEFINER
-- SET search_path = public, private, pg_temp
-- AS $fn$
-- DECLARE
--   caller_role text;
-- BEGIN
--   caller_role := private.current_user_role();  -- align with live helper
--
--   -- ONLY the approval transition is gated here. Every other transition
--   -- delegates to the original enforcement logic, unchanged.
--   IF NEW.state = 'approved' AND OLD.state IS DISTINCT FROM 'approved' THEN
--     IF caller_role NOT IN ('estimator', 'admin') THEN
--       RAISE EXCEPTION 'Only estimators and admins may approve a quote'
--         USING ERRCODE = '42501';
--     END IF;
--   END IF;
--
--   RETURN NEW;
-- END;
-- $fn$;
--
-- -- Chain: replace the trigger's function with the checking wrapper.
-- -- The ORIGINAL function's logic must be preserved — if the original is
-- -- itself a trigger function returning NEW, prefer wrapping it (call it
-- -- from the wrapper after the role check) rather than re-deriving its
-- -- transition table. Confirm the exact call shape from Step 1's output.
--
-- DROP TRIGGER IF EXISTS enforce_quote_state_transition ON public.quotes;
-- CREATE TRIGGER enforce_quote_state_transition
--   BEFORE INSERT OR UPDATE ON public.quotes
--   FOR EACH ROW EXECUTE FUNCTION
--   public.enforce_quote_state_transition_checked();
--
-- COMMIT;
--
-- ---------------------------------------------------------------------
-- Step 4 (POST-APPLY VERIFY): rerun section 2 of VERIFY_phase_1a.sql.
-- Both sales-rep probes must return blocked = true.
-- ---------------------------------------------------------------------

-- =====================================================================
-- ROLLBACK GUIDANCE
--   Capture the original trigger definition (Step 1 output) BEFORE
--   applying. Rollback:
--     DROP TRIGGER IF EXISTS enforce_quote_state_transition ON public.quotes;
--     -- re-create the ORIGINAL trigger exactly as captured in Step 1
--     DROP FUNCTION IF EXISTS public.enforce_quote_state_transition_checked();
--   The original enforcement function is never dropped by this file.
-- =====================================================================
