-- =====================================================================
-- Phase 1A / Migration D — OPTIONAL foreign-key indexes.
--
-- *** DEFERRED — NOT PART OF THE MINIMAL PHASE 1A DEPLOYMENT. ***
--
-- This file is PERFORMANCE ONLY: it contains no security change. The
-- minimal Phase 1A deployment consists of migrations A, B and C only —
-- no approval-transition fix is needed (server-side approval
-- authorization is verified in the live trigger function). Do NOT apply
-- this migration as part of Phase 1A.
--
-- Keep it for a later performance pass, run with the DBA's own review.
--
-- EVIDENCE BASIS (repository only; no database inspection was performed)
--   Column names taken from src/lib/database.types.ts and join/filter usage:
--     lead_intakes.assigned_rep_id, .claimed_by, .converted_quote_id,
--       .duplicate_of_lead_id
--     quotes.lead_id, .owner_id, .requested_by, .reviewed_by, .approved_by
--     quote_wbs_lines.quote_id, quote_cost_items.quote_id
--     quote_versions.quote_id, quote_pdfs.quote_id, notifications.quote_id
--   Confirmed already indexed: quotes.last_reviewed_by
--     (quotes_last_reviewed_by_idx, docs/SESSION_5B_PERMISSIONS.sql).
--   Unknown: which of these indexes already exist under a different name —
--     run VERIFY_phase_1a.sql section 9 first and trim duplicates.
--
-- LOCKING NOTE: plain CREATE INDEX takes a SHARE lock and blocks writes on
-- that table for the duration. On a small dataset this is milliseconds. If
-- these tables have grown, run the CONCURRENTLY variants instead — those
-- CANNOT run inside a transaction block, so run them one at a time.
-- =====================================================================

-- Everything below is illustrative for the later pass. Review against
-- section 9 of VERIFY_phase_1a.sql before running any of it.

-- CREATE INDEX IF NOT EXISTS lead_intakes_assigned_rep_id_idx   ON public.lead_intakes(assigned_rep_id);
-- CREATE INDEX IF NOT EXISTS lead_intakes_claimed_by_idx        ON public.lead_intakes(claimed_by);
-- CREATE INDEX IF NOT EXISTS lead_intakes_converted_quote_id_idx ON public.lead_intakes(converted_quote_id);
-- CREATE INDEX IF NOT EXISTS lead_intakes_duplicate_of_lead_idx ON public.lead_intakes(duplicate_of_lead_id);
-- CREATE INDEX IF NOT EXISTS quotes_lead_id_idx                 ON public.quotes(lead_id);
-- CREATE INDEX IF NOT EXISTS quotes_owner_id_idx                ON public.quotes(owner_id);
-- CREATE INDEX IF NOT EXISTS quotes_requested_by_idx            ON public.quotes(requested_by);
-- CREATE INDEX IF NOT EXISTS quotes_reviewed_by_idx             ON public.quotes(reviewed_by);
-- CREATE INDEX IF NOT EXISTS quotes_approved_by_idx             ON public.quotes(approved_by);
-- CREATE INDEX IF NOT EXISTS quote_wbs_lines_quote_id_idx       ON public.quote_wbs_lines(quote_id);
-- CREATE INDEX IF NOT EXISTS quote_cost_items_quote_id_idx      ON public.quote_cost_items(quote_id);
-- CREATE INDEX IF NOT EXISTS quote_versions_quote_id_idx        ON public.quote_versions(quote_id);
-- CREATE INDEX IF NOT EXISTS quote_pdfs_quote_id_idx            ON public.quote_pdfs(quote_id);
-- CREATE INDEX IF NOT EXISTS notifications_quote_id_idx         ON public.notifications(quote_id);

-- =====================================================================
-- ROLLBACK GUIDANCE
--   Every statement above is CREATE INDEX IF NOT EXISTS. Rollback is
--   DROP INDEX <name>; for any index the DBA decides was unnecessary.
--   Nothing here touches data, RLS, policies or functions.
-- =====================================================================
