/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as GetAQuoteRouteImport } from './routes/get-a-quote'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyQuotesRouteImport } from './routes/my-quotes'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as QuotesIndexRouteImport } from './routes/quotes.index'
import { Route as QuotesIdRouteImport } from './routes/quotes.$id'
import { Route as QuotesNewRouteImport } from './routes/quotes.new'
import { Route as RequestQuoteIndexRouteImport } from './routes/request-quote.index'
import { Route as RequestQuoteIdRouteImport } from './routes/request-quote.$id'
import { Route as ReviewIndexRouteImport } from './routes/review.index'
import { Route as ReviewIdRouteImport } from './routes/review.$id'
import { Route as AuthenticatedDebugCatalogRouteImport } from './routes/_authenticated/debug/catalog'
import { Route as RequestQuoteConfirmationIdRouteImport } from './routes/request-quote.confirmation.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const GetAQuoteRoute = GetAQuoteRouteImport.update({
  id: '/get-a-quote',
  path: '/get-a-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyQuotesRoute = MyQuotesRouteImport.update({
  id: '/my-quotes',
  path: '/my-quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesIndexRoute = QuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesIdRoute = QuotesIdRouteImport.update({
  id: '/quotes/$id',
  path: '/quotes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesNewRoute = QuotesNewRouteImport.update({
  id: '/quotes/new',
  path: '/quotes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestQuoteIndexRoute = RequestQuoteIndexRouteImport.update({
  id: '/request-quote/',
  path: '/request-quote/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestQuoteIdRoute = RequestQuoteIdRouteImport.update({
  id: '/request-quote/$id',
  path: '/request-quote/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIdRoute = ReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDebugCatalogRoute =
  AuthenticatedDebugCatalogRouteImport.update({
    id: '/debug/catalog',
    path: '/debug/catalog',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const RequestQuoteConfirmationIdRoute =
  RequestQuoteConfirmationIdRouteImport.update({
    id: '/request-quote/confirmation/$id',
    path: '/request-quote/confirmation/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/get-a-quote': typeof GetAQuoteRoute
  '/login': typeof LoginRoute
  '/my-quotes': typeof MyQuotesRoute
  '/notifications': typeof NotificationsRoute
  '/pipeline': typeof PipelineRoute
  '/signup': typeof SignupRoute
  '/quotes/$id': typeof QuotesIdRoute
  '/quotes/new': typeof QuotesNewRoute
  '/request-quote/$id': typeof RequestQuoteIdRoute
  '/review/$id': typeof ReviewIdRoute
  '/quotes/': typeof QuotesIndexRoute
  '/request-quote/': typeof RequestQuoteIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/debug/catalog': typeof AuthenticatedDebugCatalogRoute
  '/request-quote/confirmation/$id': typeof RequestQuoteConfirmationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/get-a-quote': typeof GetAQuoteRoute
  '/login': typeof LoginRoute
  '/my-quotes': typeof MyQuotesRoute
  '/notifications': typeof NotificationsRoute
  '/pipeline': typeof PipelineRoute
  '/signup': typeof SignupRoute
  '/quotes/$id': typeof QuotesIdRoute
  '/quotes/new': typeof QuotesNewRoute
  '/request-quote/$id': typeof RequestQuoteIdRoute
  '/review/$id': typeof ReviewIdRoute
  '/quotes': typeof QuotesIndexRoute
  '/request-quote': typeof RequestQuoteIndexRoute
  '/review': typeof ReviewIndexRoute
  '/debug/catalog': typeof AuthenticatedDebugCatalogRoute
  '/request-quote/confirmation/$id': typeof RequestQuoteConfirmationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/get-a-quote': typeof GetAQuoteRoute
  '/login': typeof LoginRoute
  '/my-quotes': typeof MyQuotesRoute
  '/notifications': typeof NotificationsRoute
  '/pipeline': typeof PipelineRoute
  '/signup': typeof SignupRoute
  '/quotes/$id': typeof QuotesIdRoute
  '/quotes/new': typeof QuotesNewRoute
  '/request-quote/$id': typeof RequestQuoteIdRoute
  '/review/$id': typeof ReviewIdRoute
  '/quotes/': typeof QuotesIndexRoute
  '/request-quote/': typeof RequestQuoteIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/_authenticated/debug/catalog': typeof AuthenticatedDebugCatalogRoute
  '/request-quote/confirmation/$id': typeof RequestQuoteConfirmationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/get-a-quote'
    | '/login'
    | '/my-quotes'
    | '/notifications'
    | '/pipeline'
    | '/signup'
    | '/quotes/$id'
    | '/quotes/new'
    | '/request-quote/$id'
    | '/review/$id'
    | '/quotes/'
    | '/request-quote/'
    | '/review/'
    | '/debug/catalog'
    | '/request-quote/confirmation/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/get-a-quote'
    | '/login'
    | '/my-quotes'
    | '/notifications'
    | '/pipeline'
    | '/signup'
    | '/quotes/$id'
    | '/quotes/new'
    | '/request-quote/$id'
    | '/review/$id'
    | '/quotes'
    | '/request-quote'
    | '/review'
    | '/debug/catalog'
    | '/request-quote/confirmation/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/get-a-quote'
    | '/login'
    | '/my-quotes'
    | '/notifications'
    | '/pipeline'
    | '/signup'
    | '/quotes/$id'
    | '/quotes/new'
    | '/request-quote/$id'
    | '/review/$id'
    | '/quotes/'
    | '/request-quote/'
    | '/review/'
    | '/_authenticated/debug/catalog'
    | '/request-quote/confirmation/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  GetAQuoteRoute: typeof GetAQuoteRoute
  LoginRoute: typeof LoginRoute
  MyQuotesRoute: typeof MyQuotesRoute
  NotificationsRoute: typeof NotificationsRoute
  PipelineRoute: typeof PipelineRoute
  SignupRoute: typeof SignupRoute
  QuotesIdRoute: typeof QuotesIdRoute
  QuotesNewRoute: typeof QuotesNewRoute
  RequestQuoteIdRoute: typeof RequestQuoteIdRoute
  ReviewIdRoute: typeof ReviewIdRoute
  QuotesIndexRoute: typeof QuotesIndexRoute
  RequestQuoteIndexRoute: typeof RequestQuoteIndexRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
  RequestQuoteConfirmationIdRoute: typeof RequestQuoteConfirmationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-a-quote': {
      id: '/get-a-quote'
      path: '/get-a-quote'
      fullPath: '/get-a-quote'
      preLoaderRoute: typeof GetAQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-quotes': {
      id: '/my-quotes'
      path: '/my-quotes'
      fullPath: '/my-quotes'
      preLoaderRoute: typeof MyQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/': {
      id: '/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof QuotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/$id': {
      id: '/quotes/$id'
      path: '/quotes/$id'
      fullPath: '/quotes/$id'
      preLoaderRoute: typeof QuotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/new': {
      id: '/quotes/new'
      path: '/quotes/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof QuotesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-quote/': {
      id: '/request-quote/'
      path: '/request-quote'
      fullPath: '/request-quote/'
      preLoaderRoute: typeof RequestQuoteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-quote/$id': {
      id: '/request-quote/$id'
      path: '/request-quote/$id'
      fullPath: '/request-quote/$id'
      preLoaderRoute: typeof RequestQuoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$id': {
      id: '/review/$id'
      path: '/review/$id'
      fullPath: '/review/$id'
      preLoaderRoute: typeof ReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/debug/catalog': {
      id: '/_authenticated/debug/catalog'
      path: '/debug/catalog'
      fullPath: '/debug/catalog'
      preLoaderRoute: typeof AuthenticatedDebugCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/request-quote/confirmation/$id': {
      id: '/request-quote/confirmation/$id'
      path: '/request-quote/confirmation/$id'
      fullPath: '/request-quote/confirmation/$id'
      preLoaderRoute: typeof RequestQuoteConfirmationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDebugCatalogRoute: typeof AuthenticatedDebugCatalogRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDebugCatalogRoute: AuthenticatedDebugCatalogRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  GetAQuoteRoute: GetAQuoteRoute,
  LoginRoute: LoginRoute,
  MyQuotesRoute: MyQuotesRoute,
  NotificationsRoute: NotificationsRoute,
  PipelineRoute: PipelineRoute,
  SignupRoute: SignupRoute,
  QuotesIdRoute: QuotesIdRoute,
  QuotesNewRoute: QuotesNewRoute,
  RequestQuoteIdRoute: RequestQuoteIdRoute,
  ReviewIdRoute: ReviewIdRoute,
  QuotesIndexRoute: QuotesIndexRoute,
  RequestQuoteIndexRoute: RequestQuoteIndexRoute,
  ReviewIndexRoute: ReviewIndexRoute,
  RequestQuoteConfirmationIdRoute: RequestQuoteConfirmationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
